services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    hostname: api-server
    networks:
      - backend-network
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
      - redis-cache
      - minio-s3
  
  postgres:
    image: postgres:15
    container_name: postgresDB
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: always

  redis-cache:
    image: redis:7.4-alpine
    container_name: redisCache
    networks:
      - backend-network
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    restart: always
    volumes:
      - redis_data:/data
  minio-s3:
    image: minio/minio
    container_name: minioS3
    environment:
      - MINIO_ROOT_USER=${MINIO_ID}
      - MINIO_ROOT_PASSWORD=${MINIO_KEY}
    command: server /data
    networks:
      - backend-network
    ports:
      - "${MINIO_WEB_PORT}:${MINIO_WEB_PORT}"
    volumes:
      - miniodata:/data
    restart: always

  createbuckets:
    image: minio/mc
    depends_on:
      - minio-s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio-s3:${MINIO_PORT} ${MINIO_ID} ${MINIO_KEY};
      /usr/bin/mc mb --ignore-existing myminio/images;
      /usr/bin/mc policy set public myminio/images;
      exit 0;
      "

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"         
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
    networks:
      - backend-network
    depends_on:
      - api-server       # API 서버가 먼저 실행된 후 NGINX 실행

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker 엔진과 통신하기 위한 핵심 설정
      - portainer_data:/data # 설정 데이터 저장
    ports:
      - "9000:9000"
      - "9443:9443"

volumes:
  pgdata:
  redis_data:
  miniodata:
  portainer_data:
  nginx_logs:

networks:
  backend-network:
    driver: bridge 