version: '3.8'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    networks:
      - backend-network
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
      - redis-cache
      - minio-s3
  
  postgres:
    image: postgres:15
    container_name: postgresDB
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: always

  redis-cache:
    image: redis:7.4-alpine
    container_name: redisCache
    networks:
      - backend-network
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    restart: always
    volumes:
      - redis_data:/data
  minio-s3:
    image: minio/minio
    container_name: minioS3
    environment:
      - MINIO_ROOT_USER=${MINIO_ID}
      - MINIO_ROOT_PASSWORD=${MINIO_KEY}
    command: server /data
    networks:
      - backend-network
    ports:
      - "${MINIO_WEB_PORT}:${MINIO_WEB_PORT}"
    volumes:
      - miniodata:/data
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"         
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api-server       # API 서버가 먼저 실행된 후 NGINX 실행

volumes:
  pgdata:
  redis_data:
  miniodata:

networks:
  backend-network:
    driver: bridge 